### ISSUE TITLE
git lfs pull

### ISSUE THREAD

**Issue by chenting0324** [inikdom/rnn-speech#29]
Hello~When I run "git lfs pull",the problem is as follows:

CX@computer MINGW32 ~/Desktop/rnn-speech (master)
$ git lfs pull
Git LFS: (0 of 1 files) 0 B / 96.83 MB
batch response: API rate limit exceeded for 172.16.40.28. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

How to solve it?

**Comment by AMairesse** [comment]
Hi,
Given your comment on #23 I suspect that you tried quite a number of times to download the file using git-lfs. Github have a limit on download per ip adress and your ip have reached the max quota.
You should try to use your user account to do the download or simply wait some days for the quota limit to be reset.
About your error message in #23 I don't know what it can be.It's strictly related to git-lfs and I'm only a user of this software, I don't know more about it. You should look into https://git-lfs.github.com for information or some help about it.
