### ISSUE TITLE
Parameter

### ISSUE THREAD

**Issue by chenting0324** [inikdom/rnn-speech#33]
Hi! I want to run stt.py in Spyder(Anaconda),but I don't how to pass the parameter("--file data/LibriSpeech/dev-clean/2086/149220/2086-149220-0007.flac")
When I push the button "run" it only ran stt.py but didn't have any parameter?So How can I run the stt.py with the parameter in Spyder rather than input the follow command in the cmd.
python3 stt.py --file data/LibriSpeech/dev-clean/2086/149220/2086-149220-0007.flac

The follow is the error when I run the stt.py in Spyder,I konw it didn't include any parameter,but I don't know How to pass the parameter,.
usage: stt.py [-h] [--config CONFIG] [--tb_name TB_NAME]
              [--max_epoch MAX_EPOCH] [--learn_rate LEARN_RATE] [--timeline]
              (--train | --file FILE | --record | --evaluate)
stt.py: error: one of the arguments --train --file --record --evaluate is required
C:\Program Files\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2889: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
An exception has occurred, use %tb to see the full traceback.

Thank you!

**Comment by AMairesse** [comment]
Hi,
I don't know this editor but I think should add the arguments in `Run -> Configure` like explained here : http://stackoverflow.com/questions/18502876/how-to-execute-python-3-3-script-in-spyder-console-with-variables
